# Generated by Django 4.0 on 2021-12-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0001_initial'),
        ('inspection_items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionitem',
            name='id',
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='qr_code',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qr_codes.qrcode'),
            preserve_default=False,
        ),
    ]
