# Generated by Django 4.0 on 2021-12-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_forms', '0004_remove_inspectionform_inspection_items'),
        ('inspection_items', '0002_remove_inspectionitem_id_inspectionitem_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection_forms.inspectionform'),
        ),
    ]
