# Generated by Django 4.0.1 on 2022-03-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0002_inspectionitemfilters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InspectionItemFilters',
        ),
    ]
