# Generated by Django 4.0 on 2021-12-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_account'),
        ('inspection_items', '0003_inspectionitem_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
            preserve_default=False,
        ),
    ]
