# Generated by Django 4.0.1 on 2022-03-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0003_delete_inspectionitemfilters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='inspection_interval',
            field=models.TextField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annually', 'Semi-Annually'), ('annually', 'Annually')], max_length=50),
        ),
    ]
