# Generated by Django 4.0 on 2021-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0004_inspectionitem_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='inspection_type',
            field=models.TextField(choices=[('facility', 'Facility'), ('ppe', 'PPE'), ('equipment', 'Equipment'), ('rescue', 'Rescue Equipment'), ('first aid', 'First Aid'), ('vehicle', 'Vehicle'), ('other', 'Other')], max_length=50),
        ),
    ]
