# Generated by Django 4.0.1 on 2022-03-30 10:42

from django.db import migrations, models
import django.db.models.deletion
import inspection_items.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0004_alter_inspectionitem_inspection_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='is_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('serial_number', models.CharField(blank=True, max_length=250, null=True)),
                ('model_number', models.CharField(blank=True, max_length=250, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('failed_inspection', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, max_length=1000, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=inspection_items.models.qr_directory_path)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspection_items.inspectionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
