# Generated by Django 4.0.1 on 2022-03-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0005_inspectionitem_is_kit_subitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='kit',
            new_name='inspection_item',
        ),
    ]
