# Generated by Django 4.0 on 2021-12-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_account'),
        ('inspection_items', '0005_alter_inspectionitem_inspection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
        ),
    ]
