# Generated by Django 4.0.1 on 2022-03-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0006_rename_kit_subitem_inspection_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subitem',
            old_name='inspection_item',
            new_name='kit',
        ),
    ]
