# Generated by Django 4.0 on 2021-12-31 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0002_qrcode_image'),
        ('inspection_items', '0006_alter_inspectionitem_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='qr_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qr_codes.qrcode'),
        ),
    ]
