# Generated by Django 4.0 on 2022-01-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0007_inspectionitem_id_alter_inspectionitem_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
