# Generated by Django 4.0.1 on 2022-04-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0007_rename_inspection_item_subitem_kit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionitem',
            options={'permissions': [('inspect_assigned_equipment', 'User can inspect their own equipment')]},
        ),
    ]
