# Generated by Django 4.0 on 2022-01-03 11:55

from django.db import migrations, models
import inspection_items.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0008_alter_inspectionitem_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitem',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=inspection_items.models.qr_directory_path),
        ),
    ]
