# Generated by Django 4.0 on 2022-01-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0009_alter_inspectionitem_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
