# Generated by Django 4.0 on 2022-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0010_inspectionitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
