# Generated by Django 4.0 on 2022-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0011_inspectionitem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='failed_inpsection',
            field=models.BooleanField(default=False),
        ),
    ]
