# Generated by Django 4.0 on 2022-01-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0012_inspectionitem_failed_inpsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionitem',
            old_name='failed_inpsection',
            new_name='failed_inspection',
        ),
    ]
