# Generated by Django 4.0 on 2021-12-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection_forms', '0001_initial'),
        ('inspection_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionform',
            name='inspection_items',
            field=models.ManyToManyField(to='inspection_items.InspectionItem'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_forms.inspectionform'),
        ),
        migrations.AddField(
            model_name='fielditem',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_forms.formfield'),
        ),
        migrations.AddField(
            model_name='checkboxfield',
            name='form_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_forms.formfield'),
        ),
    ]
