# Generated by Django 4.0 on 2021-12-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_items', '0001_initial'),
        ('inspection_forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionform',
            name='inspection_items',
            field=models.ManyToManyField(null=True, to='inspection_items.InspectionItem'),
        ),
    ]
