# Generated by Django 4.0 on 2021-12-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_forms', '0004_remove_inspectionform_inspection_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielditem',
            name='form_field',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='form',
        ),
        migrations.DeleteModel(
            name='CheckboxField',
        ),
        migrations.DeleteModel(
            name='FieldItem',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
