# Generated by Django 4.0 on 2022-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_forms', '0005_remove_fielditem_form_field_remove_formfield_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inspectionform',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
