# Generated by Django 4.0.1 on 2022-02-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_create_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
