# Generated by Django 4.0 on 2021-12-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='authentication.account'),
        ),
    ]
