# Generated by Django 4.0 on 2022-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[('0', 'User'), ('1', 'App Inspector'), ('2', 'App Admin'), ('3', 'System Admin')], default=0),
        ),
    ]
