# Generated by Django 4.0 on 2022-01-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[('0', 'User'), ('1', 'Inspector'), ('2', 'Account Admin'), ('3', 'Superuser')], default=0),
        ),
    ]
