# Generated by Django 4.0.1 on 2022-04-14 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('enterprise', 'Enterprise'), ('trial', 'Trial')], max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.TextField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default='customer', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.subscription'),
        ),
    ]
