# Generated by Django 4.0 on 2022-01-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[('base_user', 'User'), ('inspector', 'Inspector'), ('account_admin', 'Account Admin'), ('system_admin', 'Superuser')], default=0),
        ),
    ]
