# Generated by Django 4.0 on 2022-01-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('base_user', 'User'), ('inspector', 'Inspector'), ('account_admin', 'Account Admin'), ('system_admin', 'Superuser')], default=0, max_length=250),
        ),
    ]
