# Generated by Django 4.0.1 on 2022-01-10 22:05

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=2000)),
                ('image', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='qr-codes/')),
                ('data', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
