# Generated by Django 4.0 on 2021-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(default='test.txt', upload_to='qr-codes/'),
            preserve_default=False,
        ),
    ]
