# Generated by Django 4.0 on 2022-01-02 18:59

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0002_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='qr-codes/'),
        ),
    ]
