# Generated by Django 4.0.1 on 2022-01-10 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection_forms', '0001_initial'),
        ('inspection_items', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('json', models.JSONField()),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('completed_past_due', models.BooleanField()),
                ('failed_inspection', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.account')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspection_forms.inspectionform')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspection_items.inspectionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
