# Generated by Django 4.0 on 2022-01-08 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection_forms', '0006_inspectionform_is_active_inspectionform_is_deleted'),
        ('authentication', '0005_create_superuser'),
        ('inspection_items', '0011_inspectionitem_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('json', models.JSONField()),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('failed_inspection', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.account')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.user')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspection_forms.inspectionform')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inspection_items.inspectionitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
