# Generated by Django 4.0 on 2022-01-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='completed_past_due',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspection',
            name='due_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
