# Generated by Django 4.0.1 on 2022-03-13 00:07

from django.db import migrations, models
import django.db.models.deletion
import inspections.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=inspections.models.qr_directory_path)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
