# Generated by Django 4.0 on 2022-01-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_completed_past_due_inspection_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='due_date',
        ),
    ]
