# Generated by Django 4.0.1 on 2022-03-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_inspection_completed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='completed_past_due',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
