# Generated by Django 4.0.1 on 2022-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_alter_inspection_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='failed_inspection',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
